// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2m0RKqjnK_qtlHJJs7IMr1MXxpNgIXKo',
    appId: '1:860975537168:web:2acd0f1f80aa625080be95',
    messagingSenderId: '860975537168',
    projectId: 'mayaring',
    authDomain: 'mayaring.firebaseapp.com',
    storageBucket: 'mayaring.appspot.com',
    measurementId: 'G-5MFML0L8ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4homOcsvgQTQLKxPM8gNzkmFQnNPTlVA',
    appId: '1:860975537168:android:bf3a2a286df6f01180be95',
    messagingSenderId: '860975537168',
    projectId: 'mayaring',
    storageBucket: 'mayaring.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIzzpW0wbG5XbA76P2aBt4uA6h5nus_to',
    appId: '1:860975537168:ios:1084594a9794043080be95',
    messagingSenderId: '860975537168',
    projectId: 'mayaring',
    storageBucket: 'mayaring.appspot.com',
    iosClientId:
        '860975537168-sdvr9ap5rb3in5ilsprjdv3hq24r29b1.apps.googleusercontent.com',
    iosBundleId: 'com.org.nimanthaliyan.weddingPlanner',
  );
}
